name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: ./src/MySweetHome/
      run: dotnet restore
    - name: Build
      working-directory: ./src/MySweetHome/
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./src/MySweetHome/
      run: dotnet test -p:CollectCoverage=true -p:CoverletOutput=./coverage/lcov.info -p:CoverletOutputFormat=lcov
      
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: /home/runner/work/MySweetHome/MySweetHome/src/MySweetHome/MySweetHome.Domain.Tests/coverage/lcov.info
        
